# Generated by Django 4.1.5 on 2026-01-02 21:00

from django.db import migrations


def create_basic_seeds(apps, schema_editor):
    """Create basic seed set (Parsnip-style) for simple mode."""
    Item = apps.get_model('mythgarden', 'Item')

    # Basic seeds - simple names, all with growth_days=1 for 2-day cycle (SEED->SPROUT->CROP)
    basic_seeds = [
        {'name': 'Parsnip Seed', 'price': 1, 'rarity': 'COMMON', 'growth_days': 1, 'effort_time': 15},
        {'name': 'Potato Seed', 'price': 2, 'rarity': 'COMMON', 'growth_days': 1, 'effort_time': 15},
        {'name': 'Rhubarb Seed', 'price': 3, 'rarity': 'UNCOMMON', 'growth_days': 1, 'effort_time': 15},
        {'name': 'Cauliflower Seed', 'price': 4, 'rarity': 'UNCOMMON', 'growth_days': 1, 'effort_time': 15},
        {'name': 'Melon Seed', 'price': 5, 'rarity': 'RARE', 'growth_days': 1, 'effort_time': 15},
        {'name': 'Pumpkin Seed', 'price': 6, 'rarity': 'RARE', 'growth_days': 1, 'effort_time': 15},
        {'name': 'Mythfruit Seed', 'price': 7, 'rarity': 'EPIC', 'growth_days': 1, 'effort_time': 15},
    ]

    for seed_data in basic_seeds:
        Item.objects.get_or_create(
            name=seed_data['name'],
            defaults={
                'item_type': 'SEED',
                'price': seed_data['price'],
                'rarity': seed_data['rarity'],
                'growth_days': seed_data['growth_days'],
                'effort_time': seed_data['effort_time'],
            }
        )


def remove_basic_seeds(apps, schema_editor):
    """Remove basic seeds if migration is reversed."""
    Item = apps.get_model('mythgarden', 'Item')

    basic_seed_names = [
        'Parsnip Seed', 'Potato Seed', 'Rhubarb Seed', 'Cauliflower Seed',
        'Melon Seed', 'Pumpkin Seed', 'Mythfruit Seed'
    ]

    Item.objects.filter(name__in=basic_seed_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0075_populate_game_settings'),
    ]

    operations = [
        migrations.RunPython(create_basic_seeds, remove_basic_seeds),
    ]
