# Generated by Django 4.1.5 on 2023-01-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quandary',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1023),
        ),
    ]
