# Generated by Django 4.1.5 on 2023-01-07 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_alter_quandary_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landscape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='landscapes/')),
                ('keywords', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Portrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portraits/')),
                ('keywords', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='quandary',
            name='description',
        ),
        migrations.AddField(
            model_name='quandary',
            name='parent_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_quandary', to='adventure.answer'),
        ),
        migrations.AddField(
            model_name='hero',
            name='portrait',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heroes', to='adventure.portrait'),
        ),
        migrations.AddField(
            model_name='quandary',
            name='landscape',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adventure.landscape'),
        ),
    ]
