# Generated by Django 4.1.5 on 2023-01-08 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_landscape_portrait_remove_quandary_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quandary',
            name='parent_answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='child_quandary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_answer', to='adventure.quandary'),
        ),
    ]
