# Generated by Django 4.1.5 on 2023-01-08 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_alter_answer_child_quandary_alter_hero_portrait_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quandary',
            name='landscape',
        ),
        migrations.AddField(
            model_name='landscape',
            name='quandary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adventure.quandary'),
        ),
    ]
