# Generated by Django 4.1.5 on 2023-01-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0007_alter_landscape_image_alter_portrait_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landscape',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='landscapes/'),
        ),
        migrations.AlterField(
            model_name='portrait',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portraits/'),
        ),
    ]
