# Generated by Django 4.1.5 on 2023-01-09 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0008_alter_landscape_image_alter_portrait_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landscape',
            name='quandary',
        ),
        migrations.AddField(
            model_name='quandary',
            name='landscape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adventure.landscape'),
        ),
    ]
