# Generated by Django 4.1.5 on 2023-01-09 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0009_remove_landscape_quandary_quandary_landscape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='answers_given',
        ),
    ]
