# Generated by Django 4.1.5 on 2023-01-19 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='buildings/')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='portraits/')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='items/')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='places/')),
            ],
        ),
        migrations.CreateModel(
            name='Clock',
            fields=[
                ('hero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mythgarden.hero')),
                ('days', models.CharField(choices=[(0, 'Sun'), (1, 'Mon'), (2, 'Tue'), (3, 'Wed'), (4, 'Thu'), (5, 'Fri'), (6, 'Sat')], max_length=1)),
                ('time', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('hero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mythgarden.hero')),
                ('money', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Villager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='portraits/')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mythgarden.building')),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.ManyToManyField(blank=True, null=True, to='mythgarden.item')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mythgarden.hero')),
                ('occupants', models.ManyToManyField(blank=True, null=True, to='mythgarden.villager')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mythgarden.place')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mythgarden.place'),
        ),
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_1_relative_direction', models.CharField(choices=[(0, 'North'), (1, 'East'), (2, 'South'), (3, 'West')], max_length=1)),
                ('place_2_relative_direction', models.CharField(choices=[(0, 'North'), (1, 'East'), (2, 'South'), (3, 'West')], max_length=1)),
                ('place_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_1', to='mythgarden.place')),
                ('place_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_2', to='mythgarden.place')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('cost_amount', models.IntegerField(default=0)),
                ('cost_unit', models.CharField(choices=[(0, 'm'), (1, 'h'), (2, 'd'), (3, '₭')], max_length=1)),
                ('action_type', models.CharField(choices=[(0, 'Travel'), (1, 'Talk'), (2, 'Plant'), (3, 'Water'), (4, 'Harvest'), (5, 'Buy'), (6, 'Sell')], max_length=1)),
                ('direction', models.CharField(blank=True, choices=[(0, 'North'), (1, 'East'), (2, 'South'), (3, 'West')], max_length=1, null=True)),
                ('log_statement', models.CharField(max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Rucksack',
            fields=[
                ('hero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mythgarden.hero')),
                ('contents', models.ManyToManyField(blank=True, null=True, to='mythgarden.item')),
            ],
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['content_type', 'object_id'], name='mythgarden__content_5a9c98_idx'),
        ),
    ]
