# Generated by Django 4.1.5 on 2023-01-19 19:04

from django.db import migrations, models
import django.db.models.deletion
import mythgarden.models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0005_alter_clock_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.IntegerField(blank=True, choices=[('SEED', 'Seed'), ('SHOOT', 'Shoot'), ('CROP', 'Crop'), ('GIFT', 'Gift')], null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('TRAVEL', 'Travel'), ('TALK', 'Talk'), ('GIFT', 'Gift'), ('PLANT', 'Plant'), ('WATER', 'Water'), ('HARVEST', 'Harvest'), ('BUY', 'Buy'), ('SELL', 'Sell')], max_length=7),
        ),
        migrations.AlterField(
            model_name='action',
            name='cost_unit',
            field=models.CharField(choices=[('MINUTE', 'm'), ('HOUR', 'h'), ('DAY', 'd'), ('KOIN', '₭')], max_length=6),
        ),
        migrations.AlterField(
            model_name='situation',
            name='place',
            field=models.ForeignKey(default=mythgarden.models.Place.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='mythgarden.place'),
        ),
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='landmarks/')),
                ('landmark_type', models.IntegerField(blank=True, choices=[(0, 'Field'), (1, 'Shop'), (2, 'House')], null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='mythgarden.place')),
            ],
        ),
        migrations.AlterField(
            model_name='villager',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mythgarden.landmark'),
        ),
        migrations.DeleteModel(
            name='Building',
        ),
    ]
