# Generated by Django 4.1.5 on 2023-01-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0006_item_item_type_item_price_alter_action_action_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='cost_amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='clock',
            name='day',
            field=models.CharField(choices=[('SUN', 'Sun'), ('MON', 'Mon'), ('TUE', 'Tue'), ('WED', 'Wed'), ('THU', 'Thu'), ('FRI', 'Fri'), ('SAT', 'Sat')], max_length=9),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('SEED', 'Seed'), ('SHOOT', 'Shoot'), ('CROP', 'Crop'), ('GIFT', 'Gift')], default='GIFT', max_length=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='landmark_type',
            field=models.CharField(choices=[('FIELD', 'Field'), ('SHOP', 'Shop'), ('HOUSE', 'House')], default='HOUSE', max_length=5),
        ),
    ]
