# Generated by Django 4.1.5 on 2023-01-19 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0007_alter_action_cost_amount_alter_clock_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villager',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mythgarden.landmark'),
        ),
    ]
