# Generated by Django 4.1.5 on 2023-01-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0010_action_secondary_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bridge',
            name='place_1_relative_direction',
        ),
        migrations.RemoveField(
            model_name='bridge',
            name='place_2_relative_direction',
        ),
        migrations.AddField(
            model_name='bridge',
            name='direction_1',
            field=models.CharField(choices=[('NORTH', 'North'), ('EAST', 'East'), ('SOUTH', 'South'), ('WEST', 'West')], default='WEST', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bridge',
            name='direction_2',
            field=models.CharField(choices=[('NORTH', 'North'), ('EAST', 'East'), ('SOUTH', 'South'), ('WEST', 'West')], default='EAST', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='direction',
            field=models.CharField(blank=True, choices=[('NORTH', 'North'), ('EAST', 'East'), ('SOUTH', 'South'), ('WEST', 'West')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('SEED', 'Seed'), ('SPROUT', 'Sprout'), ('CROP', 'Crop'), ('GIFT', 'Gift')], default='GIFT', max_length=6),
        ),
    ]
