# Generated by Django 4.1.5 on 2023-01-22 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0011_remove_bridge_place_1_relative_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situation',
            name='hero',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mythgarden.hero'),
        ),
    ]
