# Generated by Django 4.1.5 on 2023-01-22 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0012_alter_situation_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situation',
            name='hero',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='situation', to='mythgarden.hero'),
        ),
    ]
