# Generated by Django 4.1.5 on 2023-01-23 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0013_alter_situation_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='time',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(24.0)]),
        ),
    ]
