# Generated by Django 4.1.5 on 2023-01-26 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0015_rename_rucksack_inventory_alter_clock_day.py'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mythgarden.place')),
                ('surround', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='mythgarden.place')),
            ],
            bases=('mythgarden.place',),
        ),
        migrations.CreateModel(
            name='PlaceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.ManyToManyField(blank=True, to='mythgarden.item')),
                ('occupants', models.ManyToManyField(blank=True, to='mythgarden.villager')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='mythgarden.place')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('key', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('location', models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mythgarden.place')),
            ],
        ),
        migrations.CreateModel(
            name='VillagerSessionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affinity', models.IntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villagers', to='mythgarden.place')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villager_states', to='mythgarden.session')),
                ('villager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='mythgarden.villager')),
            ],
        ),
        migrations.RemoveField(
            model_name='landmark',
            name='place',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='contents',
            new_name='items',
        ),
        migrations.RemoveField(
            model_name='clock',
            name='hero',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='id',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='hero',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='hero',
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(default='Squall', max_length=255),
        ),
        migrations.DeleteModel(
            name='Situation',
        ),
        migrations.AddField(
            model_name='placestate',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_states', to='mythgarden.session'),
        ),
        migrations.AddField(
            model_name='clock',
            name='session',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mythgarden.session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='session',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mythgarden.session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='session',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mythgarden.session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='session',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mythgarden.session'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='villager',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mythgarden.building'),
        ),
        migrations.DeleteModel(
            name='Landmark',
        ),
    ]
