# Generated by Django 4.1.5 on 2023-01-26 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0016_building_placestate_session_villagersessiondata_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VillagerSessionData',
            new_name='VillagerState',
        ),
        migrations.AddField(
            model_name='clock',
            name='fake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='fake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='fake',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='clock',
            name='hero',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='hero',
        ),
        migrations.AddField(
            model_name='clock',
            name='session',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mythgarden.session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placestate',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='place_states', to='mythgarden.session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='session',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mythgarden.session'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(default='Squall', max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='location',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mythgarden.place'),
        ),
    ]
