# Generated by Django 4.1.5 on 2023-01-26 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0017_rename_villagersessiondata_villagerstate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='fake',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='items',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='hero',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='id',
        ),
        migrations.AddField(
            model_name='hero',
            name='session',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mythgarden.session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='session',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='mythgarden.session'),
            preserve_default=False,
        ),
    ]
