# Generated by Django 4.1.5 on 2023-01-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0019_remove_inventory_id_alter_inventory_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='items',
            field=models.ManyToManyField(blank=True, to='mythgarden.item'),
        ),
    ]
