# Generated by Django 4.1.5 on 2023-01-26 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0020_inventory_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clock',
            name='fake',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='fake',
        ),
        migrations.RemoveField(
            model_name='session',
            name='fake',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='fake',
        ),
    ]
