# Generated by Django 4.1.5 on 2023-01-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0021_remove_clock_fake_remove_inventory_fake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='land_type',
            field=models.CharField(choices=[('FARM', 'Farm'), ('SHOP', 'Shop'), ('WILD', 'Wild'), ('HOME', 'Home')], default='WILD', max_length=4),
        ),
    ]
