# Generated by Django 4.1.5 on 2023-03-16 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mythgarden', '0043_rename_first_session_session_is_first_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='hero',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='current_session', to='mythgarden.hero'),
            preserve_default=False,
        ),
    ]
